# numpy: làm việc với mảng
+ khi tạo mạng đa chiều ( 2 chiều, 3 chiều ...) các phần tử trong từng mảng con phải có số lượng đồng nhất như nhau
+ khi tạo mảng có nhiều kiểu dữ liệu khác nhau, numpy sẽ chuyển tất cả về 1 kiểu dữ liệu để đảm bảo tính đồng nhât

+ `np.random.rand(x, y)`: mảng với các giá trị ngẫu nhiên, x hàng y cột -> output la các giá trị từ 0.0 đến 1.0

In [19]:
import numpy as np 

#Mảng toàn số 0
zeros = np.zeros((2, 3))
print(zeros)

# Mảng toàn số 1
ones = np.ones((3, 3))
print(ones)

# Mảng với các giá trị ngẫu nhiên
random = np.random.rand(3, 4)
print(random)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.48492861 0.65888623 0.50239902 0.60829713]
 [0.44693439 0.350174   0.3115799  0.94635328]
 [0.10885053 0.60831241 0.68846533 0.44144272]]


+ `np.linspace(start, stop, num)`: tạo phần tử trong khoảng từ start đến stop với số phần tử là num

In [17]:
# Tạo mảng từ 0 đến 10 với khoảng cách 2
arange = np.arange(0, 10, 2) 
print(arange)

# Tạo mảng với số lượng phần tử cho trước
linspace = np.linspace(0, 10, 5)  
print(linspace)

[0 2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]


+ `ndim` xem mảng đó là mảng mấy chiều
+ `shape` kích thước của mảng đó -> ouput: (x, y) trong đó x là số hàng, y là số cột
+ `sizw` tổng số các phần tử có trong mảng

In [18]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.ndim)  
print(arr.shape) 
print(arr.size) 


2
(2, 3)
6


+ có thể dùng chỉ mục trong numpy tương tự list

In [20]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[1, 2]) 

arr[1, 2] = 10
print(arr) 

6
[[ 1  2  3]
 [ 4  5 10]]


+ numpy có thể dùng các toán tử + - * / ....

In [22]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 + arr2) 

print(arr1 * arr2) 

print(arr1 // arr2)

[5 7 9]
[ 4 10 18]
[0 0 0]


+ hàm

In [23]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.min())  
print(arr.max())  
print(arr.sum()) 
print(arr.mean()) 


1
5
15
3.0


+ `reshape` tách mảng

In [25]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape((2, 3)) 
print( reshaped )

[[1 2 3]
 [4 5 6]]


+ `flatten` gộp mảng

In [26]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
flat = arr.flatten()  
print(flat)

[1 2 3 4 5 6]
